# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.define "manager" do |manager|
    manager.vm.box = "ubuntu/xenial64"
    manager.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    manager.vm.provision "shell", inline: "apt-get update -y"
    manager.vm.provision "shell", path: "install-docker.sh"
    manager.vm.network :private_network, :ip => "192.168.10.100"
  end
  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/xenial64"
    worker1.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    worker1.vm.provision "shell", inline: "apt-get update -y"
    worker1.vm.provision "shell", path: "install-docker.sh"
    worker1.vm.network :private_network, :ip => "192.168.10.101"
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/xenial64"
    worker2.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    worker2.vm.provision "shell", inline: "apt-get update -y"
    worker2.vm.provision "shell", path: "install-docker.sh"
    worker2.vm.network :private_network, :ip => "192.168.10.102"
  end

  config.vm.provision :hosts do |hosts_config|
    hosts_config.add_host "192.168.10.100", ["manager.vagrantup.internal"]
    hosts_config.add_host "192.168.10.101", ["worker1.vagrantup.internal"]
    hosts_config.add_host "192.168.10.102", ["worker2.vagrantup.internal"]
  end
end
