Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "pacman -Syu --noconfirm"
  config.vm.provision "shell", inline: "pacman -S base-devel fd git neovim ripgrep unzip --noconfirm"
  config.vm.provision "shell", path: "setup_rust.sh", privileged: false
  config.vm.provision "shell",
    inline: "git clone https://github.com/nvim-lua/kickstart.nvim.git /home/vagrant/.config/nvim",
    privileged: false
end
