Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "pacman -Syu --noconfirm"
  config.vm.provision "shell", path: "setup.sh"
  config.vm.provision "shell", path: "setup_user.sh", privileged: false
end
