# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/buster64"
    debian.disksize.size = "20GB"
    debian.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    debian.vm.provision "shell", path: "setup.sh"
    debian.vm.provision "shell", path: "setup_rust.sh", privileged: false
  end
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
end
