# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/stretch64"
    debian.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    debian.vm.provision "shell", inline: "apt-get update -y"
    debian.vm.provision "shell", inline: "apt-get install -y curl"
    debian.vm.provision "shell", path: "setup_musl.sh"
    debian.vm.provision "shell", path: "setup_rust.sh", privileged: false
  end
end
