# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = 'azure'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    azure.vm_image_urn = 'canonical:ubuntuserver:16.04-LTS:latest'
    azure.vm_name = 'base-ubuntu-1604'
    azure.resource_group_name = 'cw-vagrant-experimental'
    azure.location = 'northeurope'
    azure.wait_for_destroy  = 'true'
  end
  config.vm.provision "shell", path: "setup.sh"
end
