Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "apt-get update -y"
  config.vm.provision "shell", inline: "apt-get install -y gcc"
  config.vm.provision "shell", path: "setup_docker.sh"
  config.vm.provision "shell", path: "setup_rust.sh", privileged: false
end
